version: '3.8'

services:
  postgresql:
    image: postgres:13.7-alpine
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  shareit-server:
    build: ./server
    ports:
      - "9090:9090"
    depends_on:
      - postgresql
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432


  shareit-gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - shareit-server
    environment:
      - SERVER_HOST=shareit-server
      - SERVER_PORT=9090