-- INSERT INTO users (name, email)
-- VALUES
-- ('Jack', 'Jack@mail.ru'),
-- ('John', 'John@mail.ru');
--
-- INSERT INTO items (name, description, available, id_user, id_request)
-- VALUES
-- ('item1', 'desc1', true, 1, null),
-- ('item2', 'desc2', false, 2, null);